title: Center for Neuroscience and Innovative Drug Development
email: hangao@cpu.edu.cn
description: >-
  The Center for Neuroscience and Innovative Drug Development at China Pharmaceutical University advances mechanism-based, sex-informed precision therapies for neurological and psychiatric disorders.
baseurl: "/CNSPDD-CPU"
url: "https://cnspdd-cpu.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: Research and Platforms
    url: /research/
  - title: Publications
    url: /publications/
  - title: PI Team
    url: /pi/
  - title: News
    url: /news/
  - title: Jobs
    url: /jobs/
  - title: Contact
    url: /contact/

# Chinese Navigation
navigation_cn:
  - title: 主页
    url: /cn/
  - title: 研究与平台
    url: /cn/research/
  - title: 论文
    url: /cn/publications/
  - title: PI团队
    url: /cn/pi/
  - title: 新闻
    url: /cn/news/
  - title: 招聘
    url: /cn/jobs/
  - title: 联系方式
    url: /cn/contact/

# Social links
social_links:
  google_scholar:
  github: CNSPDD-CPU
  linkedin:
  twitter:

# Other settings
show_excerpts: true
permalink: /:categories/:year/:month/:day/:title/
